//! Durable compaction audit records and commit receipts.

use serde_json::Value;

use super::{NewCheckpoint, Seq, SessionId};

mod receipt;

pub use receipt::CommittedCompaction;

/// Versioned compaction audit fact written to the journal.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CompactionReason {
    /// Automatic compaction crossed the soft threshold.
    SoftThreshold,
    /// Automatic compaction crossed the hard threshold.
    HardThreshold,
    /// The provider rejected the request as context-too-long.
    Emergency,
}

impl CompactionReason {
    /// Returns the stable value persisted in journal payloads.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::SoftThreshold => "soft_threshold",
            Self::HardThreshold => "hard_threshold",
            Self::Emergency => "emergency",
        }
    }
}

/// Stable pass names persisted as part of the compaction audit record.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CompactionPassKind {
    /// Complete tool outputs were externalized before replacement by markers.
    ArtifactSpill,
    /// Authorized tool results were reduced without semantic summarization.
    ToolResultSlimming,
    /// A provider generated a structured continuity summary.
    SemanticSummary,
    /// The audit event and checkpoint committed atomically.
    AtomicCommit,
}

impl CompactionPassKind {
    /// Returns the stable value persisted in journal payloads.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ArtifactSpill => "artifact_spill",
            Self::ToolResultSlimming => "tool_result_slimming",
            Self::SemanticSummary => "semantic_summary",
            Self::AtomicCommit => "atomic_commit",
        }
    }
}

/// Audit metadata describing why compaction ran and which passes contributed.
#[derive(Clone, Debug, PartialEq)]
pub struct CompactionMetadata {
    reason: CompactionReason,
    passes: Vec<CompactionPassKind>,
    summary_json: Option<Value>,
    model: Option<String>,
    token_usage_json: Option<Value>,
}

impl CompactionMetadata {
    /// Creates metadata for a deterministic compaction event.
    pub fn new(reason: CompactionReason, passes: Vec<CompactionPassKind>) -> Self {
        Self {
            reason,
            passes,
            summary_json: None,
            model: None,
            token_usage_json: None,
        }
    }

    /// Attaches the summary generated by this event and its provider cost.
    pub fn with_generated_summary(
        mut self,
        summary_json: Value,
        model: impl Into<String>,
        token_usage_json: Value,
    ) -> Self {
        self.summary_json = Some(summary_json);
        self.model = Some(model.into());
        self.token_usage_json = Some(token_usage_json);
        self
    }

    /// Returns the stable trigger reason.
    pub const fn reason(&self) -> CompactionReason {
        self.reason
    }

    /// Returns passes in execution order.
    pub fn passes(&self) -> &[CompactionPassKind] {
        &self.passes
    }

    /// Returns the summary generated by this event, when semantic summarization ran.
    pub const fn summary_json(&self) -> Option<&Value> {
        self.summary_json.as_ref()
    }

    /// Returns the summary model for this event.
    pub fn model(&self) -> Option<&str> {
        self.model.as_deref()
    }

    /// Returns provider usage incurred by this event's summary.
    pub const fn token_usage_json(&self) -> Option<&Value> {
        self.token_usage_json.as_ref()
    }
}

/// Versioned compaction audit fact written to the journal.
#[derive(Clone, Debug, PartialEq)]
pub struct CompactionEvent {
    input_hash: String,
    output_hash: String,
    source_seq_start: Seq,
    source_seq_end: Seq,
    metadata: CompactionMetadata,
}

impl CompactionEvent {
    /// Binds candidate input and installed output to the facts changed by this event.
    pub fn new(
        input_hash: impl Into<String>,
        output_hash: impl Into<String>,
        source_range: std::ops::RangeInclusive<Seq>,
        metadata: CompactionMetadata,
    ) -> Self {
        let source_seq_start = *source_range.start();
        let source_seq_end = *source_range.end();
        Self {
            input_hash: input_hash.into(),
            output_hash: output_hash.into(),
            source_seq_start,
            source_seq_end,
            metadata,
        }
    }

    /// Returns the stable input digest used to reject stale candidates.
    pub fn input_hash(&self) -> &str {
        &self.input_hash
    }

    /// Returns the digest of the exact active messages installed by the checkpoint.
    pub fn output_hash(&self) -> &str {
        &self.output_hash
    }

    /// Returns the first journal sequence changed by this event.
    pub const fn source_seq_start(&self) -> Seq {
        self.source_seq_start
    }

    /// Returns the last journal sequence changed by this event.
    pub const fn source_seq_end(&self) -> Seq {
        self.source_seq_end
    }

    /// Returns the reason, passes, and semantic-summary cost for this event.
    pub const fn metadata(&self) -> &CompactionMetadata {
        &self.metadata
    }
}

/// Complete input for an atomic compaction commit.
#[derive(Clone, Debug)]
pub struct NewCompactionCommit {
    /// Candidate's session, which must match the checkpoint.
    pub session_id: SessionId,
    /// Journal head observed during candidate generation and used as transaction CAS.
    pub expected_journal_head: Seq,
    /// Compaction audit fact appended to the journal.
    pub event: CompactionEvent,
    /// Active-context checkpoint installed in the compaction event's transaction.
    pub checkpoint: NewCheckpoint,
}
